// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYTctSFYNz2Pc0rgTb4AeXE96GAzvFkDY',
    appId: '1:530898952844:web:d7fb3b2e4710bd95a951a9',
    messagingSenderId: '530898952844',
    projectId: 'emergency-blood-bank',
    authDomain: 'emergency-blood-bank.firebaseapp.com',
    databaseURL: 'https://emergency-blood-bank-default-rtdb.firebaseio.com',
    storageBucket: 'emergency-blood-bank.firebasestorage.app',
    measurementId: 'G-BCTDM9LMVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKAy-j1FrJVMqpr4BsNw92hmP3TkFvkdM',
    appId: '1:530898952844:android:fe1aba57d4c8815ba951a9',
    messagingSenderId: '530898952844',
    projectId: 'emergency-blood-bank',
    databaseURL: 'https://emergency-blood-bank-default-rtdb.firebaseio.com',
    storageBucket: 'emergency-blood-bank.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbP3uQF9G66mmzHrJWp4QLPmgRIcXNk9s',
    appId: '1:530898952844:ios:19e134403511751aa951a9',
    messagingSenderId: '530898952844',
    projectId: 'emergency-blood-bank',
    databaseURL: 'https://emergency-blood-bank-default-rtdb.firebaseio.com',
    storageBucket: 'emergency-blood-bank.firebasestorage.app',
    iosBundleId: 'com.example.emergencyBloodBank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbP3uQF9G66mmzHrJWp4QLPmgRIcXNk9s',
    appId: '1:530898952844:ios:19e134403511751aa951a9',
    messagingSenderId: '530898952844',
    projectId: 'emergency-blood-bank',
    databaseURL: 'https://emergency-blood-bank-default-rtdb.firebaseio.com',
    storageBucket: 'emergency-blood-bank.firebasestorage.app',
    iosBundleId: 'com.example.emergencyBloodBank',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYTctSFYNz2Pc0rgTb4AeXE96GAzvFkDY',
    appId: '1:530898952844:web:ba4f2c2b714d43b0a951a9',
    messagingSenderId: '530898952844',
    projectId: 'emergency-blood-bank',
    authDomain: 'emergency-blood-bank.firebaseapp.com',
    databaseURL: 'https://emergency-blood-bank-default-rtdb.firebaseio.com',
    storageBucket: 'emergency-blood-bank.firebasestorage.app',
    measurementId: 'G-G68Z1SG7QJ',
  );
}
